# Generated by Django 5.0.7 on 2024-08-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explosion',
            name='emissionFactor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='explosiveType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='toolUsage',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('naturalGas', 'NaturalGas')], default='Diesel', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='transport',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('naturalGas', 'NaturalGas')], default='Diesel', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='area',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='bare_land',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='coal_type',
            field=models.CharField(choices=[('UnderGround', 'UnderGround'), ('OpenCast', 'OpenCast')], default='UnderGround', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='green_area',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='mine_area',
            field=models.FloatField(default=0, null=True),
        ),
    ]
