# Generated by Django 5.0.7 on 2024-08-31 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0002_alter_explosion_emissionfactor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minedetail',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='minedetail',
            name='longitude',
        ),
        migrations.CreateModel(
            name='mineaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('country', models.CharField(default='India', max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
